### ISSUE TITLE
M8 not completed section "iOS Jailbreak Detection"

### ISSUE THREAD

**Issue by sergiomarotco** [OWASP/www-project-mobile-top-10#14]
![image](https://user-images.githubusercontent.com/29877074/153164044-34e38dee-2407-4cd6-b491-2011bbea1125.png)

**Comment by Sulfkain** [comment]
hello,
This will be easy to fix if you get what you already have on MSTG
https://github.com/OWASP/owasp-mstg/blob/master/Document/0x06j-Testing-Resiliency-Against-Reverse-Engineering.md#jailbreak-detection-mstg-resilience-1

It's ok if we send a PR with that?
